<?php /**
* Assoto: dynamic loading of javascript, stylesheets, meta tags, etc.
*
* @author Kaloyan Tsvetkov (KT) <kaloyan@kaloyan.info>
* @package Assoto
* @link https://github.com/kktsvetkov/assoto/
* @license http://opensource.org/licenses/LGPL-3.0 GNU Lesser General Public License, version 3.0
*/

namespace Assoto;

/**
* Javascript (JS) Assets
*
* The script blocks ("<script>...</script>") and script files
* ("<script type=text/javascript' src='...'>") are usually attached to the
* bottom of the HTML, right before the closing "</body>" tag
*/
class JS
{
	/**
	* Adds an inline script block
	*
	* Adds a script block as an asset, which will appear as
	* "<script>...</script>" inserted at the bottom of the HTML, right
	* before the closing "</body>" tag
	*
	* @param string $script Javascript code for the script block; don't
	*	add the "<script>" tags wrapping the code, that will be added
	*	by this method
	* @param string $id (optional) identifier for this asset; if left empty
	*	it will be generated by this method
	* @param string $tack (optional) what stack to add this script block to,
	*	default value is "footer"
	*/
	public static function inline($script, $id = '', $stack = Stack::STACK_FOOTER)
	{
		$stack = (string) $stack;

		if (empty($id))
		{
			$id = count(Stack::stack($stack));
		}

		return Stack::add(
			(string) $stack,
			'<script type="text/javascript">' . $script . '</script>',
			'js:' . $id
		);
	}

	/**
	* Adds a javascript file
	*
	* Adds a javascript file as an asset, which will appear as
	* "<script type=text/javascript' src='...'>" inserted at the bottom of
	* the HTML, right before the closing "</body>" tag
	*
	* @param string $script Javascript file
	* @param string $id (optional) identifier for this asset; if left empty
	*	it will be generated by this method
	* @param array $extra (optional) extra attributes for the script block,
	* 	such as "type", "integrity", "crossorigin", etc.
	* @param string $stack (optional) what stack to add this script block to,
	*	default value is "footer"
	*/
	public static function file($script, $id = '', array $extra = array(), $stack = Stack::STACK_FOOTER)
	{
		$extra += array(
			'type' => 'text/javascript',
			);
		$extra['src'] = $script;

		if (empty($id))
		{
			$id = $script;
		}

		return Stack::add(
			(string) $stack,
			'<script ' . HTML::attributes($extra) . '/>',
			'js:' . $id
		);
	}
}
